### ISSUE TITLE
implement one of the widgets in React

### ISSUE THREAD

**Issue by x1B** [LaxarJS/shop-demo#27]
To showcase how LaxarJS can mediate between frameworks, let's implement the article-teaser-widget in React.

**Comment by x1B** [comment]
Fixed on `master` (`v1.10.0`).

**Comment by jpommerening** [comment]
@x1B: I think you missed one: https://github.com/LaxarJS/shop-demo/blob/master/includes/widgets/shop-demo/article-teaser-widget/article-teaser-widget.jsx#L68 ;)

**Comment by x1B** [comment]
doh! :sweat_smile:
